sonar.projectKey=milab
sonar.projectName=milab
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.scss
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/routes/api/**/*.js,src/routes/web/**/*.js,src/routes/middlewares/**/*.js,src/app.js,src/milab_routes.js
sonar.cpd.exclusions=src/routes/api/**/*.js,src/routes/web/**/*.js

sonar.issue.ignore.multicriteria=s3776_api,s3776_security,s3776_menu
sonar.issue.ignore.multicriteria.s3776_api.ruleKey=javascript:S3776
sonar.issue.ignore.multicriteria.s3776_api.resourceKey=src/routes/api/**/*.js
sonar.issue.ignore.multicriteria.s3776_security.ruleKey=javascript:S3776
sonar.issue.ignore.multicriteria.s3776_security.resourceKey=src/routes/middlewares/security-logger.js
sonar.issue.ignore.multicriteria.s3776_menu.ruleKey=javascript:S3776
sonar.issue.ignore.multicriteria.s3776_menu.resourceKey=src/libs/menu.js

sonar.sourceEncoding=UTF-8
