services:
  milabud:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.dev
    container_name: milabud_local
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - docker_default
    depends_on:
      - dbpostgres

  dbpostgres:
    image: postgres:latest
    container_name: local_db
    env_file:
      - .env
    #restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: ${DB_USER}
      # You can use whatever password you like
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      # <Port exposed> : < Port running inside container>
      - '5432:5432'
    networks:
      - docker_default
    expose:
      # Opens port 3306 on the container
      - '5432'
      # Where our data will be persisted
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ../sql-scripts/db_structure.sql:/docker-entrypoint-initdb.d/01_db_structure.sql:ro
      - ../sql-scripts/db_seed_system.sql:/docker-entrypoint-initdb.d/02_db_seed_system.sql:ro
      - ../sql-scripts/db_structure_prestamos.sql:/docker-entrypoint-initdb.d/03_db_structure_prestamos.sql:ro
      - ../sql-scripts/db_seed_prestamos.sql:/docker-entrypoint-initdb.d/04_db_seed_prestamos.sql:ro
      - my-db6:/var/lib/postgresql:rw

# Names our volume
volumes:
  my-db6:

networks:
  docker_default:
